--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JackNoordhuis/PocketMine-Plugins
branches:
- patch-3
projects:
  CombatLogger:
    path: CombatLogger/
  EffectEventTesting:
    path: EffectEventTesting/
  ExplosiveArrows:
    path: ExplosiveArrows/
  EffectEventTesting:
    path: EffectEventTesting/
  InteractEventTesting:
    path: InteractEventTesting/
...
